repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        exclude: bimeasuresapi/flask_toolkits/
        args: [
          "--remove-all-unused-imports",
          "--remove-unused-variables",
          "--ignore-init-module-imports",
          "--in-place",
          "--recursive",
          "."
        ]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
    -   id: reorder-python-imports

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
    -   id: autopep8
        args: [
          "--max-line-length 100"
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.1
    hooks:
      - id: mypy

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-isort
        args: [
          "--force-single-line-imports"
        ]
